openapi: 3.0.3
info:
  title: XML OJP 2.0 API
  description: API that returns trip data in XML format.
  version: 0.0.1

servers:
  - url: https://api.example.com

paths:
  /ojp:
    post:
      summary: Main /ojp endpoint
      description: Main /ojp endpoint
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/OJP"
        "500":
          description: Server error

components:
  schemas:
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__PointOfInterestCategoryStructure
    PointOfInterestCategory:
      type: object
      xml:
        name: PointOfInterestCategory  
      properties:
        osmTag:
          type: object
          required:
            - tag
            - value
          properties:
            tag:
              type: string
              xml:
                name: Tag
            value:
              type: string
              xml:
                name: Value
          xml:
            name: OsmTag

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__StopPointStructure
    StopPoint:
      type: object
      xml:
        name: StopPoint
      required:
        - stopPointRef
        - stopPointName
      properties:
        stopPointRef:
          type: string
          xml:
            name: StopPointRef
        stopPointName:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: StopPointName
        plannedQuay:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: PlannedQuay
        estimatedQuay:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: EstimatedQuay

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__StopPlaceStructure
    StopPlace:
      type: object
      xml:
        name: StopPoint
      required:
        - stopPointRef
        - stopPointName
      properties:
        stopPlaceRef:
          type: string
          xml:
            name: StopPlaceRef
        stopPlaceName:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: StopPlaceName

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TopographicPlaceStructure
    TopographicPlace:
      type: object
      xml:
        name: StopPoint
      required:
        - topographicPlaceCode
        - topographicPlaceName
      properties:
        topographicPlaceCode:
          type: string
          xml:
            name: TopographicPlaceCode
        topographicPlaceName:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: TopographicPlaceName

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__PointOfInterestStructure
    PointOfInterest:
      type: object
      xml:
        name: PointOfInterest
      required:
        - publicCode
        - name
        - pointOfInterestCategory
      properties:
        publicCode:
          type: string
          xml:
            name: PublicCode
        name:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: Name
        pointOfInterestCategory:
          type: array
          xml:
            name: PointOfInterestCategory
          items:
            $ref: "#/components/schemas/PointOfInterestCategory"
        topographicPlaceRef:
          type: string
          xml:
            name: TopographicPlaceRef

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__AddressStructure
    Address:
      type: object
      xml:
        name: Address
      required:
        - publicCode
        - name
      properties:
        publicCode:
          type: string
          xml:
            name: PublicCode
        name:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: Name
        postCode:
          type: string
          xml:
            name: PostCode
        topographicPlaceName:
          type: string
          xml:
            name: TopographicPlaceName
        TopographicPlaceRef:
          type: string
          xml:
            name: topographicPlaceRef
        Street:
          type: string
          xml:
            name: street
        HouseNumber:
          type: string
          xml:
            name: houseNumber

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__PlaceStructure
    Place:
      type: object
      xml:
        name: Place
      required:
        - name
        - geoPosition
        - mode
      properties:
        stopPoint:
          $ref: '#/components/schemas/StopPoint'
          xml:
            name: StopPoint
        stopPlace:
          $ref: '#/components/schemas/StopPlace'
          xml:
            name: StopPlace
        topographicPlace:
          $ref: '#/components/schemas/TopographicPlace'
          xml:
            name: TopographicPlace
        pointOfInterest:
          $ref: '#/components/schemas/PointOfInterest'
          xml:
            name: PointOfInterest
        address:
          $ref: '#/components/schemas/Address'
          xml:
            name: Address
        name:
          $ref: './shared.yml#/components/schemas/InternationalText'
          xml:
            name: Name
        geoPosition:
          $ref: './shared.yml#/components/schemas/GeoPosition'
          xml:
            name: GeoPosition
        mode:
          type: array
          xml:
            name: PtMode
          items:
            $ref: './shared.yml#/components/schemas/VehicleModesOfTransportEnum'

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__PlaceResultStructure
    PlaceResult:
      type: object
      xml:
        name: PlaceResult
      required:
        - place
        - complete
      properties:
        place:
          $ref: '#/components/schemas/Place'
          xml:
            name: Place
        complete:
          type: boolean
          xml:
            name: Complete
        probability:
          type: number
          xml:
            name: Probability

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#element_ojp__OJPLocationInformationDelivery
    OJPLocationInformationDelivery:
      type: object
      xml:
        name: OJPLocationInformationDelivery
      required:
        - responseTimestamp
        - placeResult
      properties:
        responseTimestamp:
          type: string
          xml:
            name: ResponseTimestamp
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        requestMessageRef:
          type: string
          xml:
            name: RequestMessageRef
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        defaultLanguage:
          type: string
          xml:
            name: DefaultLanguage
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        calcTime:
          type: string
          xml:
            name: CalcTime
        placeResult:
          type: array
          xml:
            name: PlaceResult
          items:
            $ref: "#/components/schemas/PlaceResult"

    OJP:
      type: object
      xml:
        name: OJP
      required:
        - OJPResponse
      properties:
        OJPResponse:
          type: object
          xml:
            name: OJPResponse
          required:
            - serviceDelivery
          properties:
            serviceDelivery:
              type: object
              xml:
                name: ServiceDelivery
                namespace: "http://www.siri.org.uk/siri"
                prefix: siri
              required:
                - responseTimestamp
                - producerRef
                - OJPLocationInformationDelivery
              properties:
                responseTimestamp:
                  type: string
                  xml:
                    name: ResponseTimestamp
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                producerRef:
                  type: string
                  xml:
                    name: ProducerRef
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                OJPLocationInformationDelivery:
                  $ref: '#/components/schemas/OJPLocationInformationDelivery'
                  xml:
                    name: OJPLocationInformationDelivery
    # OJP
        