openapi: 3.0.3
info:
  title: XML OJP 2.0 API
  description: API that returns trip data in XML format.
  version: 0.0.1

servers:
  - url: https://api.example.com

paths:
  /ojp:
    post:
      summary: Main /ojp endpoint
      description: Main /ojp endpoint
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/OJP"
        "500":
          description: Server error

components:
  schemas:
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__LegBoardStructure
    LegBoard:
      type: object
      xml:
        name: LegBoard
      allOf:
        - $ref: './shared.yml#/components/schemas/CallAtStop'
      required:
        - stopPointRef
        - stopPointName
        - serviceDeparture

    LegIntermediate:
      type: object
      xml:
        name: LegIntermediate
      allOf:
        - $ref: './shared.yml#/components/schemas/CallAtStop'
      required:
        - stopPointRef
        - stopPointName
        - serviceArrival
        - serviceDeparture

    LegAlight:
      type: object
      xml:
        name: LegAlight
      allOf:
        - $ref: './shared.yml#/components/schemas/CallAtStop'
      required:
        - stopPointRef
        - stopPointName
        - serviceArrival

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__LinearShapeStructure
    LinkProjection:
      type: object
      xml:
        name: LinkProjection
      required:
        - position
      properties:
        position:
          type: array
          xml:
            name: Position
          items:
            $ref: './shared.yml#/components/schemas/GeoPosition'

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TrackSectionStructure
    TrackSection:
      type: object
      xml:
        name: TrackSection
      properties:
        trackSectionStart:
          $ref: './shared.yml#/components/schemas/PlaceRef'
          xml:
            name: TrackSectionStart
        trackSectionEnd:
          $ref: './shared.yml#/components/schemas/PlaceRef'
          xml:
            name: TrackSectionEnd
        linkProjection:
          $ref: '#/components/schemas/LinkProjection'
          xml:
            name: LinkProjection
    
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__LegTrackStructure
    LegTrack:
      type: object
      xml:
        name: LegTrack
      required:
        - trackSection
      properties:
        trackSection:
          $ref: '#/components/schemas/TrackSection'
          xml:
            name: TrackSection

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__ContinuousServiceStructure
    ContinuousService:
      type: object
      xml:
        name: ContinuousService
      properties:
        personalModeOfOperation:
          # TODO - add enum?
          type: string
          xml:
            name: PersonalModeOfOperation
        personalMode:
          # TODO - add enum?
          type: string
          xml:
            name: PersonalMode

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TimedLegStructure
    TimedLeg:
      type: object
      xml:
        name: TimedLeg
      required:
        - legBoard
        - legIntermediate
        - legAlight
        - service
      properties:
        legBoard:
          $ref: '#/components/schemas/LegBoard'
          xml:
            name: LegBoard
        legIntermediate:
          type: array
          xml:
            name: LegIntermediate
          items:
            $ref: "#/components/schemas/LegIntermediate"
        legAlight:
          $ref: '#/components/schemas/LegAlight'
          xml:
            name: LegAlight
        service:
          $ref: './shared.yml#/components/schemas/DatedJourney'
          xml:
            name: Service
        legTrack:
          $ref: '#/components/schemas/LegTrack'
          xml:
            name: LegTrack
    # TimedLeg

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TransferLegStructure
    TransferLeg:
      type: object
      xml:
        name: TransferLeg
      required:
        - transferType
        - legStart
        - legEnd
        - duration
      properties:
        # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TransferTypeEnumeration
        transferType:
          type: string
          enum: [walk, remainInVehicle]
          xml:
            name: TransferType
        legStart:
          $ref: './shared.yml#/components/schemas/PlaceRef'
          xml:
            name: LegStart
        legEnd:
          $ref: './shared.yml#/components/schemas/PlaceRef'
          xml:
            name: LegEnd
        duration:
          type: string
          xml:
            name: Duration

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__ContinuousLegStructure
    ContinuousLeg:
      type: object
      xml:
        name: ContinuousLeg
      required:
        - legStart
        - legEnd
        - service
        - duration
      properties:
        legStart:
          $ref: './shared.yml#/components/schemas/PlaceRef'
          xml:
            name: LegStart
        legEnd:
          $ref: './shared.yml#/components/schemas/PlaceRef'
          xml:
            name: LegEnd
        service:
          $ref: '#/components/schemas/ContinuousService'
          xml:
            name: Service
        duration:
          type: string
          xml:
            name: Duration

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__LegStructure
    Leg:
      type: object
      xml:
        name: Leg
      required:
        - id
      properties:
        id:
          type: string
          xml:
            name: Id
        duration:
          type: string
          xml:
            name: Duration
        # Using oneOf requires additional boilerplate code, use optionals instead
        timedLeg:
          $ref: '#/components/schemas/TimedLeg'
          xml:
            name: TimedLeg
        transferLeg:
          $ref: '#/components/schemas/TransferLeg'
          xml:
            name: TransferLeg
        continuousLeg:
          $ref: '#/components/schemas/ContinuousLeg'
          xml:
            name: ContinuousLeg
    
    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#group_ojp__TripStatusGroup
    TripStatus:
      type: object
      xml:
        name: TripStatus
      properties:
        unplanned: 
          type: boolean
          xml:
            name: Unplanned
        cancelled: 
          type: boolean
          xml:
            name: Cancelled
        deviation: 
          type: boolean
          xml:
            name: Deviation
        delayed: 
          type: boolean
          xml:
            name: delayed
        infeasible: 
          type: boolean
          xml:
            name: Infeasible
    
    Trip:
      allOf:
        - $ref: "#/components/schemas/TripStatus"
        - type: object
          xml:
            name: Trip
          required:
            - id
            - duration
            - startTime
            - endTime
            - transfers
            - leg
            - status
          properties:
            id:
              type: string
              xml:
                name: Id
            duration:
              type: string
              xml:
                name: Duration
            startTime:
              type: string
              format: date-time
              xml:
                name: StartTime
            endTime:
              type: string
              format: date-time
              xml:
                name: EndTime
            transfers:
              type: number
              xml:
                name: Transfers
            leg:
              type: array
              xml:
                name: Leg
              items:
                $ref: "#/components/schemas/Leg"

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__TripResultStructure
    TripResult:
      type: object
      xml:
        name: TripResult
      required:
        - id
        - trip
      properties:
        id:
          type: string
          xml:
            name: Id
        trip:
          $ref: '#/components/schemas/Trip'
          xml:
            name: Trip

    # https://vdvde.github.io/OJP/develop/documentation-tables/ojp.html#type_ojp__OJPTripDeliveryStructure
    OJPTripDelivery:
      type: object
      xml:
        name: OJPTripDelivery
      required:
        - responseTimestamp
        - tripResult
      properties:
        responseTimestamp:
          type: string
          xml:
            name: ResponseTimestamp
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        requestMessageRef:
          type: string
          xml:
            name: RequestMessageRef
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        defaultLanguage:
          type: string
          xml:
            name: DefaultLanguage
            namespace: "http://www.siri.org.uk/siri"
            prefix: siri
        calcTime:
          type: string
          xml:
            name: CalcTime
        tripResult:
          type: array
          xml:
            name: TripResult
          items:
            $ref: "#/components/schemas/TripResult"

    OJP:
      type: object
      xml:
        name: OJP
      required:
        - OJPResponse
      properties:
        OJPResponse:
          type: object
          xml:
            name: OJPResponse
          required:
            - serviceDelivery
          properties:
            serviceDelivery:
              type: object
              xml:
                name: ServiceDelivery
                namespace: "http://www.siri.org.uk/siri"
                prefix: siri
              required:
                - responseTimestamp
                - producerRef
                - OJPTripDelivery
              properties:
                responseTimestamp:
                  type: string
                  xml:
                    name: ResponseTimestamp
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                producerRef:
                  type: string
                  xml:
                    name: ProducerRef
                    namespace: "http://www.siri.org.uk/siri"
                    prefix: siri
                OJPTripDelivery:
                  $ref: '#/components/schemas/OJPTripDelivery'
                  xml:
                    name: OJPTripDelivery
    # OJP
        