import { XML_Config } from "./types/_all";
type DEBUG_LEVEL_Type = 'DEBUG' | 'PROD';
export declare const DEBUG_LEVEL: DEBUG_LEVEL_Type;
export declare const SDK_VERSION = "0.18.6";
export type OJP_VERSION_Type = '1.0' | '2.0';
export declare const IS_NODE_CLI: string | false;
export declare const XML_BuilderConfigOJPv1: XML_Config;
export declare const XML_ParserConfigOJPv1: XML_Config;
export declare const XML_ConfigOJPv2: XML_Config;
export {};
