import { XML_Config } from "./types/_all";
type DEBUG_LEVEL_Type = 'DEBUG' | 'PROD';
export declare const DEBUG_LEVEL: DEBUG_LEVEL_Type;
type OJP_VERSION_Type = '1.0' | '2.0';
export declare const OJP_VERSION: OJP_VERSION_Type;
export declare const SDK_VERSION = "0.17.4";
export declare const IS_NODE_CLI: string | false;
export declare const XML_Config_OJPv1: XML_Config;
export declare const XML_Config_OJPv2: XML_Config;
export declare const XML_Config_Default: XML_Config;
export declare const REQUESTOR_REF: string;
export {};
